api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:

        json: ['application/json']
        jsonld: ['application/ld+json']
        html: ['text/html']
        multipart: ['multipart/form-data']
        

